/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectTableEventIdRouteImport } from './routes/select-table.$eventId'
import { Route as EventIdRouteImport } from './routes/event.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTableEventIdRoute = SelectTableEventIdRouteImport.update({
  id: '/select-table/$eventId',
  path: '/select-table/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event/$id': typeof EventIdRoute
  '/select-table/$eventId': typeof SelectTableEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/$id': typeof EventIdRoute
  '/select-table/$eventId': typeof SelectTableEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event/$id': typeof EventIdRoute
  '/select-table/$eventId': typeof SelectTableEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/event/$id' | '/select-table/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/event/$id' | '/select-table/$eventId'
  id: '__root__' | '/' | '/event/$id' | '/select-table/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventIdRoute: typeof EventIdRoute
  SelectTableEventIdRoute: typeof SelectTableEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-table/$eventId': {
      id: '/select-table/$eventId'
      path: '/select-table/$eventId'
      fullPath: '/select-table/$eventId'
      preLoaderRoute: typeof SelectTableEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventIdRoute: EventIdRoute,
  SelectTableEventIdRoute: SelectTableEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
