/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyReservationsRouteImport } from './routes/my-reservations'
import { Route as MyQrRouteImport } from './routes/my-qr'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectTableEventIdRouteImport } from './routes/select-table.$eventId'
import { Route as ReserveEventIdRouteImport } from './routes/reserve.$eventId'
import { Route as ReservationIdRouteImport } from './routes/reservation.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'

const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrRoute = MyQrRouteImport.update({
  id: '/my-qr',
  path: '/my-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTableEventIdRoute = SelectTableEventIdRouteImport.update({
  id: '/select-table/$eventId',
  path: '/select-table/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveEventIdRoute = ReserveEventIdRouteImport.update({
  id: '/reserve/$eventId',
  path: '/reserve/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIdRoute = ReservationIdRouteImport.update({
  id: '/reservation/$id',
  path: '/reservation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-qr': typeof MyQrRoute
  '/my-reservations': typeof MyReservationsRoute
  '/event/$id': typeof EventIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reserve/$eventId': typeof ReserveEventIdRoute
  '/select-table/$eventId': typeof SelectTableEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-qr': typeof MyQrRoute
  '/my-reservations': typeof MyReservationsRoute
  '/event/$id': typeof EventIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reserve/$eventId': typeof ReserveEventIdRoute
  '/select-table/$eventId': typeof SelectTableEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-qr': typeof MyQrRoute
  '/my-reservations': typeof MyReservationsRoute
  '/event/$id': typeof EventIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reserve/$eventId': typeof ReserveEventIdRoute
  '/select-table/$eventId': typeof SelectTableEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-qr'
    | '/my-reservations'
    | '/event/$id'
    | '/reservation/$id'
    | '/reserve/$eventId'
    | '/select-table/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-qr'
    | '/my-reservations'
    | '/event/$id'
    | '/reservation/$id'
    | '/reserve/$eventId'
    | '/select-table/$eventId'
  id:
    | '__root__'
    | '/'
    | '/my-qr'
    | '/my-reservations'
    | '/event/$id'
    | '/reservation/$id'
    | '/reserve/$eventId'
    | '/select-table/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyQrRoute: typeof MyQrRoute
  MyReservationsRoute: typeof MyReservationsRoute
  EventIdRoute: typeof EventIdRoute
  ReservationIdRoute: typeof ReservationIdRoute
  ReserveEventIdRoute: typeof ReserveEventIdRoute
  SelectTableEventIdRoute: typeof SelectTableEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr': {
      id: '/my-qr'
      path: '/my-qr'
      fullPath: '/my-qr'
      preLoaderRoute: typeof MyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-table/$eventId': {
      id: '/select-table/$eventId'
      path: '/select-table/$eventId'
      fullPath: '/select-table/$eventId'
      preLoaderRoute: typeof SelectTableEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$eventId': {
      id: '/reserve/$eventId'
      path: '/reserve/$eventId'
      fullPath: '/reserve/$eventId'
      preLoaderRoute: typeof ReserveEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/reservation/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyQrRoute: MyQrRoute,
  MyReservationsRoute: MyReservationsRoute,
  EventIdRoute: EventIdRoute,
  ReservationIdRoute: ReservationIdRoute,
  ReserveEventIdRoute: ReserveEventIdRoute,
  SelectTableEventIdRoute: SelectTableEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
